// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: proto/timerservice/service.proto

package timerservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId []byte `protobuf:"bytes,1,opt,name=timerId,proto3" json:"timerId,omitempty"`
	EndTime int64  `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *AddEvent) Reset() {
	*x = AddEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEvent) ProtoMessage() {}

func (x *AddEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEvent.ProtoReflect.Descriptor instead.
func (*AddEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddEvent) GetTimerId() []byte {
	if x != nil {
		return x.TimerId
	}
	return nil
}

func (x *AddEvent) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AddManyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*AddEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *AddManyEvent) Reset() {
	*x = AddManyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddManyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddManyEvent) ProtoMessage() {}

func (x *AddManyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddManyEvent.ProtoReflect.Descriptor instead.
func (*AddManyEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddManyEvent) GetEvents() []*AddEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StopEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId []byte `protobuf:"bytes,1,opt,name=timerId,proto3" json:"timerId,omitempty"`
}

func (x *StopEvent) Reset() {
	*x = StopEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEvent) ProtoMessage() {}

func (x *StopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEvent.ProtoReflect.Descriptor instead.
func (*StopEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{2}
}

func (x *StopEvent) GetTimerId() []byte {
	if x != nil {
		return x.TimerId
	}
	return nil
}

type StartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId []byte `protobuf:"bytes,1,opt,name=timerId,proto3" json:"timerId,omitempty"`
	EndTime int64  `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *StartEvent) Reset() {
	*x = StartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvent) ProtoMessage() {}

func (x *StartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEvent.ProtoReflect.Descriptor instead.
func (*StartEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartEvent) GetTimerId() []byte {
	if x != nil {
		return x.TimerId
	}
	return nil
}

func (x *StartEvent) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type RemoveEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId []byte `protobuf:"bytes,1,opt,name=timerId,proto3" json:"timerId,omitempty"`
}

func (x *RemoveEvent) Reset() {
	*x = RemoveEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEvent) ProtoMessage() {}

func (x *RemoveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEvent.ProtoReflect.Descriptor instead.
func (*RemoveEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveEvent) GetTimerId() []byte {
	if x != nil {
		return x.TimerId
	}
	return nil
}

type TimerFinishEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *TimerFinishEvent) Reset() {
	*x = TimerFinishEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_timerservice_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerFinishEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerFinishEvent) ProtoMessage() {}

func (x *TimerFinishEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timerservice_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerFinishEvent.ProtoReflect.Descriptor instead.
func (*TimerFinishEvent) Descriptor() ([]byte, []int) {
	return file_proto_timerservice_service_proto_rawDescGZIP(), []int{5}
}

func (x *TimerFinishEvent) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_timerservice_service_proto protoreflect.FileDescriptor

var file_proto_timerservice_service_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x25, 0x0a,
	0x09, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x24, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0x88, 0x03, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x16, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x1a, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x6e,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x17, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x12, 0x19, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x54, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54,
	0x61, 0x70, 0x2d, 0x54, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_timerservice_service_proto_rawDescOnce sync.Once
	file_proto_timerservice_service_proto_rawDescData = file_proto_timerservice_service_proto_rawDesc
)

func file_proto_timerservice_service_proto_rawDescGZIP() []byte {
	file_proto_timerservice_service_proto_rawDescOnce.Do(func() {
		file_proto_timerservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_timerservice_service_proto_rawDescData)
	})
	return file_proto_timerservice_service_proto_rawDescData
}

var file_proto_timerservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_timerservice_service_proto_goTypes = []interface{}{
	(*AddEvent)(nil),         // 0: timerservice.AddEvent
	(*AddManyEvent)(nil),     // 1: timerservice.AddManyEvent
	(*StopEvent)(nil),        // 2: timerservice.StopEvent
	(*StartEvent)(nil),       // 3: timerservice.StartEvent
	(*RemoveEvent)(nil),      // 4: timerservice.RemoveEvent
	(*TimerFinishEvent)(nil), // 5: timerservice.TimerFinishEvent
	(*emptypb.Empty)(nil),    // 6: google.protobuf.Empty
}
var file_proto_timerservice_service_proto_depIdxs = []int32{
	0, // 0: timerservice.AddManyEvent.events:type_name -> timerservice.AddEvent
	0, // 1: timerservice.TimerService.Add:input_type -> timerservice.AddEvent
	1, // 2: timerservice.TimerService.AddMany:input_type -> timerservice.AddManyEvent
	3, // 3: timerservice.TimerService.Start:input_type -> timerservice.StartEvent
	2, // 4: timerservice.TimerService.Stop:input_type -> timerservice.StopEvent
	4, // 5: timerservice.TimerService.Remove:input_type -> timerservice.RemoveEvent
	6, // 6: timerservice.TimerService.TimerTick:input_type -> google.protobuf.Empty
	6, // 7: timerservice.TimerService.Add:output_type -> google.protobuf.Empty
	6, // 8: timerservice.TimerService.AddMany:output_type -> google.protobuf.Empty
	6, // 9: timerservice.TimerService.Start:output_type -> google.protobuf.Empty
	6, // 10: timerservice.TimerService.Stop:output_type -> google.protobuf.Empty
	6, // 11: timerservice.TimerService.Remove:output_type -> google.protobuf.Empty
	5, // 12: timerservice.TimerService.TimerTick:output_type -> timerservice.TimerFinishEvent
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_timerservice_service_proto_init() }
func file_proto_timerservice_service_proto_init() {
	if File_proto_timerservice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_timerservice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_timerservice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddManyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_timerservice_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_timerservice_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_timerservice_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_timerservice_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimerFinishEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_timerservice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_timerservice_service_proto_goTypes,
		DependencyIndexes: file_proto_timerservice_service_proto_depIdxs,
		MessageInfos:      file_proto_timerservice_service_proto_msgTypes,
	}.Build()
	File_proto_timerservice_service_proto = out.File
	file_proto_timerservice_service_proto_rawDesc = nil
	file_proto_timerservice_service_proto_goTypes = nil
	file_proto_timerservice_service_proto_depIdxs = nil
}
